// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pghirivvexmhidgfetqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnaGlyaXZ2ZXhtaGlkZ2ZldHFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDk0OTcsImV4cCI6MjA2MjcyNTQ5N30.YpMwoU0xItpTLrKfd7xanKZYi4VE2_-G33YUk_pV4Ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);